default_platform(:android)

before_all do 
  ensure_git_branch(
    branch: "main"
  )
  # git_pull
end

platform :android do
  lane :bump_version_code do
    path = "#{Dir.pwd}".gsub!('fastlane', 'app/build.gradle');
    re = /versionCode\s+(\d+)/ 
  
    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s
  
    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  desc "Build and publish the Android application"
  lane :build do
    gradle(task: "clean")

    bump_version_code

    gradle(
      task: "bundle",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => "#{Dir.pwd}/#{ENV['ANDROID_KEYSTORE_FILE']}",
        "android.injected.signing.store.password" => ENV['ANDROID_KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['ANDROID_KEYSTORE_ALIAS'],
        "android.injected.signing.key.password" => ENV['ANDROID_KEYSTORE_PASSWORD']
      }
    )

    upload_to_play_store(
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
      skip_upload_apk: true,
      changes_not_sent_for_review: true,
      track: 'internal'
    )
  end

  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end
