import {z} from 'zod';

export const typeSchema = z.enum([
  'suv',
  'hatchback',
  'sedan',
  'coupe',
  'convertible',
  'wagon',
  'bike',
]);

export const vehicleMakeSchema = z.enum([
  'Abarth',
  'Alfa-Romeo',
  'Aston-Martin',
  'Audi',
  'Bentley',
  'BMW',
  'Bugatti',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Citroën',
  'Dacia',
  'Daewoo',
  'Daihatsu',
  'Dodge',
  'Donkervoort',
  'DS',
  'Ferrari',
  'Fiat',
  'Fisker',
  'Ford',
  'Honda',
  'Hummer',
  'Hyundai',
  'Infiniti',
  'Iveco',
  'Jaguar',
  'Jeep',
  'Kia',
  'Lada',
  'Lamborghini',
  'Lancia',
  'Land Rover',
  'Landwind',
  'Lexus',
  'Lotus',
  'Maserati',
  'Maybach',
  'Mazda',
  'Mercedes-Benz',
  'MG',
  'Mini',
  'Mitsubishi',
  'Morgan',
  'Nissan',
  'Opel',
  'Peugeot',
  'Porsche',
  'Renault',
  'Rolls-Royce',
  'Rover',
  'Saab',
  'Seat',
  'Skoda',
  'Smart',
  'SsangYong',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
]);

export const wheelDriveSchema = z.enum(['allWheel', 'frontWheel', 'rearWheel']);

export const schema = z.object({
  id: z.string().default(''),
  // TODO: Fix this when you are ready
  // created: z
  //   .instanceof(firebase.firestore.Timestamp)
  //   .transform((ts) => ts.toDate()),
  gallery: z.array(z.string()).default([]),
  profilePicture: z.string().default(''),
  name: z.string().default(''),
  description: z.string().default(''),
  wheelDrive: wheelDriveSchema.default(wheelDriveSchema.Values.frontWheel),
  type: typeSchema.default(typeSchema.Values.hatchback),
  user: z.string().default(''),
  kw: z.number().optional(),
  torque: z.number().optional(),
  make: vehicleMakeSchema.default(vehicleMakeSchema.Values.Audi),
  model: z.string().default(''),
  year: z.number().default(2021),
  maxSpeed: z.number().default(260),
  unitOfSpeed: z.enum(['km/h', 'mph']).default('km/h'),
});

export type Type = z.infer<typeof schema>;
