name: Build and test
"on":
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest
    if: ${{ contains(github.event.head_commit.message, ':rocket:') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn ci

      - name: Run tests
        run: yarn ci:test
